Repository lemonjuiceexe/Chess, pull requests merged in 2021-01, with the labels that each got.

#1 Change Board type from GameObj to Board and remove GetComponents from it
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Piece.cs
Labels: enhancement

#3 Create legal Squares manager
  Assets/Graphics/black px.png
  Assets/Graphics/black px.png.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Piece.cs
Labels: enhancement

#5 Unselecting pieces; tint; hotfixes
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Piece.cs
Labels: bug, enhancement

#6 Bishop, rook hotifx
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Piece.cs
Labels: bug, enhancement

#7 Queen, Knight movement, pawn taking, actual moving (w/o taking)
  Assets/Prefabs/black tile.prefab
  Assets/Prefabs/black tile.prefab.meta
  Assets/Prefabs/white tile.prefab
  Assets/Prefabs/white tile.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Piece.cs
  Assets/Scripts/Square.cs
Labels: enhancement

#9 Pieces transition
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Square.cs
Labels: enhancement

#10 Taking pieces & colours
  Assets/Scripts/Board.cs
  Assets/Scripts/Piece.cs
Labels: enhancement

#12 Other colour for take, turn control, board flip
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Piece.cs
  Assets/Scripts/Square.cs
Labels: enhancement

#13 Probable fix for #8
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Piece.cs
  Assets/Scripts/Square.cs
  ProjectSettings/TagManager.asset
Labels: bug

#14 Barebone UI, debug menu, option to disable turn-based mode
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Square.cs
  Assets/Scripts/UIManager.cs
  Assets/Scripts/UIManager.cs.meta
Labels: enhancement

#15 Small debug menu improvements
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/UIManager.cs
Labels: enhancement

#16 Debug menu changes
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Piece.cs
  Assets/Scripts/Square.cs
  Assets/Scripts/UIManager.cs
Labels: enhancement

#18 King move calculation includes checks, fix for #17
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Board.cs
  Assets/Scripts/Piece.cs
  Assets/Scripts/UIManager.cs
Labels: bug, enhancement
